# Generated by Django 4.2.4 on 2023-08-20 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('profile_image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[40, 40], upload_to='img_store_profile/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.IntegerField()),
                ('available_quantity_is_displayed', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='...', null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('discount_is_displayed', models.BooleanField(default=True)),
                ('divided_times', models.IntegerField()),
                ('divided_times_interest', models.IntegerField()),
                ('divided_times_unit', models.FloatField()),
                ('image_1', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 500], upload_to='img_store_product/')),
                ('image_2', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to='img_store_product/')),
                ('image_3', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to='img_store_product/')),
                ('image_4', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to='img_store_product/')),
                ('image_5', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to='img_store_product/')),
                ('is_published', models.BooleanField(default=False)),
                ('max_quantity_per_sale', models.IntegerField()),
                ('old_price', models.FloatField()),
                ('price', models.FloatField()),
                ('registry_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('shipping', models.FloatField()),
                ('summary', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tags', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('url_text', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
