# Generated by Django 4.2.4 on 2023-08-20 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('registry_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
    ]
