# Generated by Django 4.2.4 on 2023-08-23 04:33

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StationProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[None, 40], upload_to='img_store/')),
                ('brand_image_in_nav_is_displayed', models.BooleanField(default=True)),
                ('brand_name', models.CharField(max_length=200)),
                ('brand_name_in_nav_is_displayed', models.BooleanField(default=False)),
                ('social_media_discord', models.CharField(blank=True, max_length=200, null=True)),
                ('social_media_facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('social_media_github', models.CharField(blank=True, max_length=200, null=True)),
                ('social_media_instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('social_media_linkedin', models.CharField(blank=True, max_length=200, null=True)),
                ('social_media_other', models.CharField(blank=True, max_length=200, null=True)),
                ('social_media_twitch', models.CharField(blank=True, max_length=200, null=True)),
                ('social_media_twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('social_media_whatsapp', models.CharField(blank=True, max_length=200, null=True)),
                ('social_media_youtube', models.CharField(blank=True, max_length=200, null=True)),
                ('theme_accent_color', colorfield.fields.ColorField(blank=True, default='#8A42AA', image_field=None, max_length=18, null=True, samples=None)),
                ('theme_accent_color_text', colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=18, null=True, samples=None)),
                ('theme_body_color', colorfield.fields.ColorField(blank=True, default='#ECECEC', image_field=None, max_length=18, null=True, samples=None)),
                ('theme_body_color_text', colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=18, null=True, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1000, 500], upload_to='img_station_user/')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('profile_image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[40, 40], upload_to='img_station_user/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
