# Generated by Django 4.2.4 on 2023-08-26 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StationProfileModel',
        ),
        migrations.DeleteModel(
            name='UserProfileModel',
        ),
    ]
